name: First Workflow
on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: action/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
